CREATE DATABASE GAMEPIKACHU_OOP
GO

USE GAMEPIKACHU
GO

CREATE TABLE BAN
(
	ID INT IDENTITY PRIMARY KEY, 
	TEN NVARCHAR(100),
	IDMAN INT NOT NULL,
	LEVELHIENTAI INT NOT NULL, -- 1: level1 || 2: level 2
	DAI INT NOT NULL ,
	RONG INT NOT NULL,
	SOMANG INT NOT NULL, 
	THOIGIAN INT NOT NULL,	
)
GO
CREATE TABLE TAIKHOAN
(
	TENDANGNHAP NVARCHAR(100) PRIMARY KEY NOT NULL,
	MATKHAU NVARCHAR(1000) NOT NULL,
	LOAITAIKHOAN INT  NOT NULL DEFAULT 1   --  CHUA CHAC LAM DUOC, 0 LA ADMIN VA 1 LA NGUOI CHOI
)
CREATE TABLE O
(
	ID INT IDENTITY PRIMARY KEY,
	IDPOKEMON INT REFERENCES POKEMON(ID),
	TRANGTHAI INT NOT NULL
	
)
GO
CREATE TABLE POKEMON
(
	ID INT IDENTITY PRIMARY KEY, 
	TEN NVARCHAR(50) NOT NULL, 
	DAI INT NOT NULL,
	RONG INT NOT NULL
)
GO
CREATE TABLE THONGTINCANHAN
(
	IDNGUOICHOI INT IDENTITY PRIMARY KEY, -- LAY TU TABLE TAIKHOAN
	GIOITINH INT, 
	TUOI INT, 
	TENNGUOICHOI NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100)
)
GO
CREATE TABLE PHIENCHOI
(
	ID INT IDENTITY PRIMARY KEY,
	IDNGUOICHOI INT NOT NULL,
	DIEM INT NOT NULL,
	TRANGTHAI INT NOT NULL DEFAULT 0, -- 0: DANG CHOI, 1: KETTHUC
	THOIGIANBATDAU TIMESTAMP NOT NULL,
	THOIGIANKETTHUC TIMESTAMP
)
GO
CREATE TABLE THANHTICH
(
	IDNGUOICHOI INT PRIMARY KEY NOT NULL,
	TENNGUOICHOI NVARCHAR(100),
	DIEMCAONHAT INT,
	SOPHIENCHOI INT,
	TONGTHOIGIANCHOI INT --CHUA CHAC LAM DUOC.
)
GO
CREATE TABLE MAN
(
	ID INT IDENTITY PRIMARY KEY,
	SOMANG INT NOT NULL, -- SO MANG TOI DA
	DIEMMAN INT NOT NULL, 
	IDHINHNEN INT, -- THEM HINH NEN MAC DINH O DAY
	THOIGIAN INT NOT NULL, -- TINH BANG GIAY, LA THOI GIAN TOI DA CHO MOI MAN
	SOPOKEMON INT NOT NULL,

)
GO
CREATE TABLE HINHNEN
(
	ID INT IDENTITY PRIMARY KEY,
	TEN NVARCHAR
)
GO
